In [1]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [4]:
df = df.drop(columns=["id","Unnamed: 32"])

In [5]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [6]:
x_train, x_test, y_train, y_test = train_test_split(
    df.iloc[:,1:],
    df.iloc[:,0],
    test_size=0.2,
)

In [7]:
scaler = StandardScaler()

In [8]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
x_train

array([[-0.2036765 ,  0.69615026, -0.23111492, ...,  0.18342089,
        -0.05097917, -0.81505002],
       [-0.57514241,  0.28211227, -0.63050118, ..., -0.64399102,
        -0.32776794, -0.83634344],
       [-0.71408767,  1.19392627, -0.66553506, ...,  0.22334056,
        -0.1573161 ,  0.85184221],
       ...,
       [-0.23486829,  2.65468953, -0.25460823, ..., -0.59301667,
        -1.10652956, -0.40119339],
       [-0.10159426, -0.48781231, -0.16805393, ..., -1.00127205,
        -0.8438148 , -0.670364  ],
       [-0.81616991, -1.19725943, -0.85430586, ..., -1.61434605,
        -0.22768613, -1.10496806]], shape=(455, 30))

In [10]:
x_test

array([[ 0.96176236,  0.93573404,  1.09151718, ...,  1.27967641,
        -0.94233284,  2.09122819],
       [-0.58081364, -0.29707571, -0.58639971, ..., -0.91129926,
        -0.77813611, -0.3717102 ],
       [ 0.18480312,  0.90782137,  0.3248934 , ...,  0.86666138,
         0.15074823,  0.15898724],
       ...,
       [-1.58518942, -1.74853474, -1.57353086, ..., -1.10644503,
         0.49477947,  0.33643236],
       [ 0.80580339, -0.05283982,  0.86070572, ...,  2.11952483,
         0.32120007,  0.35554184],
       [-0.80766306, -0.40407429, -0.82545443, ..., -0.4494594 ,
         0.10852622, -0.36297444]], shape=(114, 30))

In [11]:
encoder = LabelEncoder()

In [12]:
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,

In [14]:
y_test

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0])

In [15]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
x_train_tensor

tensor([[-0.2037,  0.6962, -0.2311,  ...,  0.1834, -0.0510, -0.8151],
        [-0.5751,  0.2821, -0.6305,  ..., -0.6440, -0.3278, -0.8363],
        [-0.7141,  1.1939, -0.6655,  ...,  0.2233, -0.1573,  0.8518],
        ...,
        [-0.2349,  2.6547, -0.2546,  ..., -0.5930, -1.1065, -0.4012],
        [-0.1016, -0.4878, -0.1681,  ..., -1.0013, -0.8438, -0.6704],
        [-0.8162, -1.1973, -0.8543,  ..., -1.6143, -0.2277, -1.1050]],
       dtype=torch.float64)

In [17]:
x_test_tensor

tensor([[ 0.9618,  0.9357,  1.0915,  ...,  1.2797, -0.9423,  2.0912],
        [-0.5808, -0.2971, -0.5864,  ..., -0.9113, -0.7781, -0.3717],
        [ 0.1848,  0.9078,  0.3249,  ...,  0.8667,  0.1507,  0.1590],
        ...,
        [-1.5852, -1.7485, -1.5735,  ..., -1.1064,  0.4948,  0.3364],
        [ 0.8058, -0.0528,  0.8607,  ...,  2.1195,  0.3212,  0.3555],
        [-0.8077, -0.4041, -0.8255,  ..., -0.4495,  0.1085, -0.3630]],
       dtype=torch.float64)

In [18]:
y_train_tensor

tensor([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,

In [19]:
y_test_tensor

tensor([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [30]:
class NN:
    def __init__(self, x):
        self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, x):
        z = torch.matmul(x, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()

        return loss

In [31]:
learning_rate = 0.1
epochs = 25

In [32]:
model = NN(x_train_tensor)

In [33]:
model.weights

tensor([[0.7817],
        [0.8045],
        [0.3457],
        [0.2621],
        [0.7661],
        [0.5019],
        [0.8665],
        [0.6892],
        [0.7798],
        [0.8861],
        [0.1802],
        [0.6775],
        [0.3302],
        [0.9737],
        [0.7635],
        [0.2513],
        [0.8112],
        [0.3949],
        [0.9807],
        [0.3775],
        [0.1207],
        [0.4042],
        [0.8415],
        [0.2971],
        [0.9473],
        [0.7966],
        [0.3327],
        [0.2316],
        [0.3749],
        [0.2230]], dtype=torch.float64, requires_grad=True)

In [34]:
# Creating Model
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [35]:
# Define Loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model.forward(x_train_tensor)

    # Loss Function
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward Pass
    loss.backward()

    # Parameters Update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero Gradient
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print Loss in every Epochs
    print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 3.8276341684081046
Epoch : 2, Loss : 3.712871241762023
Epoch : 3, Loss : 3.593663604660466
Epoch : 4, Loss : 3.4699679181324075
Epoch : 5, Loss : 3.342003437803341
Epoch : 6, Loss : 3.2094369204999946
Epoch : 7, Loss : 3.0769474428591757
Epoch : 8, Loss : 2.9416386693807395
Epoch : 9, Loss : 2.804307540318503
Epoch : 10, Loss : 2.6654508216577475
Epoch : 11, Loss : 2.5262428422187275
Epoch : 12, Loss : 2.3854339631290027
Epoch : 13, Loss : 2.24300750210071
Epoch : 14, Loss : 2.102187231866575
Epoch : 15, Loss : 1.964525194377741
Epoch : 16, Loss : 1.8247288034923168
Epoch : 17, Loss : 1.6891905679774533
Epoch : 18, Loss : 1.5635365255880884
Epoch : 19, Loss : 1.448685370071752
Epoch : 20, Loss : 1.3444360511756823
Epoch : 21, Loss : 1.2500505219192868
Epoch : 22, Loss : 1.168385371474858
Epoch : 23, Loss : 1.0989992897807221
Epoch : 24, Loss : 1.0408843491988327
Epoch : 25, Loss : 0.9926420213583615


In [36]:
model.weights

tensor([[ 3.9463e-01],
        [ 4.3630e-01],
        [-7.1617e-02],
        [-1.2934e-01],
        [ 2.0856e-01],
        [-1.6764e-01],
        [ 2.0910e-01],
        [ 4.4834e-02],
        [ 2.5196e-01],
        [ 4.9965e-01],
        [-2.8733e-01],
        [ 3.7679e-01],
        [-1.3241e-01],
        [ 5.8864e-01],
        [ 3.9371e-01],
        [-2.7907e-01],
        [ 3.8895e-01],
        [-1.5564e-01],
        [ 6.9005e-01],
        [-4.9888e-02],
        [-3.1463e-01],
        [ 3.1756e-02],
        [ 3.8421e-01],
        [-1.3028e-01],
        [ 4.2343e-01],
        [ 2.4121e-01],
        [-2.4988e-01],
        [-3.7182e-01],
        [-2.4889e-04],
        [-2.3884e-01]], dtype=torch.float64, requires_grad=True)

In [37]:
model.bias

tensor([-0.1136], dtype=torch.float64, requires_grad=True)

In [40]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.5).float()

    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy}")

Accuracy : 0.5221606492996216
