In [1]:
import torch

In [2]:
print(torch.__version__)

2.10.0+cpu


In [4]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name())
else:
    print("GPU not available")

GPU not available


In [5]:
torch.empty(2,3)

tensor([[2.1136e+06, 1.4013e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.5889, 0.7820, 0.8619],
        [0.4335, 0.0122, 0.9291]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])