In [1]:
import gensim
import os
import plotly.express as px
from matplotlib import pyplot as plt

from sklearn.decomposition import PCA

from nltk import sent_tokenize
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

In [2]:
stop_words = stopwords.words('english')

In [3]:
story = []

for filename in os.listdir("GOT_dataset"):
    f = open(os.path.join("GOT_dataset", filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        preprcessed_sent = simple_preprocess(sent)

        final_sent = [word for word in preprcessed_sent if word not in stop_words]
        if final_sent:
            story.append(final_sent)

In [4]:
story

[['game',
  'thrones',
  'book',
  'one',
  'song',
  'ice',
  'fire',
  'george',
  'martin',
  'prologue',
  'start',
  'back',
  'gared',
  'urged',
  'woods',
  'began',
  'grow',
  'dark',
  'around'],
 ['wildlings', 'dead'],
 ['dead', 'frighten'],
 ['ser', 'waymar', 'royce', 'asked', 'hint', 'smile'],
 ['gared', 'rise', 'bait'],
 ['old', 'man', 'past', 'fifty', 'seen', 'lordlings', 'come', 'go'],
 ['dead', 'dead', 'said'],
 ['business', 'dead'],
 ['dead'],
 ['royce', 'asked', 'softly'],
 ['proof'],
 ['saw', 'gared', 'said'],
 ['says', 'dead', 'proof', 'enough'],
 ['known', 'would', 'drag', 'quarrel', 'sooner', 'later'],
 ['wished', 'later', 'rather', 'sooner'],
 ['mother', 'told', 'dead', 'men', 'sing', 'songs', 'put'],
 ['wet', 'nurse', 'said', 'thing', 'royce', 'replied'],
 ['never', 'believe', 'anything', 'hear', 'woman', 'tit'],
 ['things', 'learned', 'even', 'dead'],
 ['voice', 'echoed', 'loud', 'twilit', 'forest'],
 ['page', 'long', 'ride', 'us', 'gared', 'pointed'],
 ['eig

In [5]:
len(story)

139066

In [6]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
)

In [7]:
model.build_vocab(story)

In [8]:
model.train(story, total_examples = model.corpus_count, epochs = model.epochs)

(4396742, 4579390)

In [9]:
model.wv.most_similar("daenerys")

[('stormborn', 0.917646050453186),
 ('unburnt', 0.8705329298973083),
 ('targaryen', 0.8414182662963867),
 ('dorne', 0.8236311078071594),
 ('elia', 0.8213382363319397),
 ('court', 0.8195633292198181),
 ('rhaella', 0.8188526630401611),
 ('myrcella', 0.8107690811157227),
 ('westeros', 0.8083334565162659),
 ('sunspear', 0.8079087734222412)]

In [10]:
model.wv.doesnt_match(["jon", "rikon", "robb", "arya", "sansa", "bran"])

'jon'

In [11]:
model.wv.doesnt_match(["cersei", "jaime", "bronn", "tyrion"])

'bronn'

In [12]:
model.wv["jon"]

array([-1.6646131 ,  0.2661388 ,  1.4826282 , -1.7718205 ,  1.1953745 ,
        0.5726263 ,  0.9860627 ,  1.3214364 ,  1.0689148 , -1.9391129 ,
       -1.2128513 , -1.3138682 , -0.63283634, -0.7212294 , -0.39956152,
        0.6877623 ,  0.08775131, -0.39791614,  0.2561126 , -0.8734968 ,
        0.08085161,  0.7577169 ,  0.21935199, -0.18724194,  1.1653292 ,
        1.1570102 , -2.0954273 ,  1.1488038 ,  0.19314489,  0.5803297 ,
       -1.937373  ,  0.24146606, -0.1556981 ,  0.8023683 , -1.4688184 ,
       -1.6389145 , -1.0439509 , -1.2902539 ,  1.0152801 , -0.46324688,
       -0.10739108, -0.00726018,  0.45691603, -0.02364645, -1.0196974 ,
       -0.05571327,  0.274307  , -0.62686545, -2.0230794 ,  2.229044  ,
        0.6475077 , -1.4379046 ,  0.26215976, -0.8434335 ,  0.69108623,
       -0.22243355,  0.47659877,  1.5431762 ,  2.2692518 ,  1.5693555 ,
       -1.0177379 , -0.9040385 ,  0.6083555 , -0.40559536, -0.2794044 ,
        0.6552444 ,  1.3301917 ,  0.38424155, -0.37665215,  0.46

In [13]:
model.wv.similarity("arya", "sansa")

np.float32(0.8120258)

In [14]:
model.wv.similarity("cersei", "sansa")

np.float32(0.6456678)

In [15]:
model.wv.similarity("tywin", "sansa")

np.float32(0.2420734)

In [16]:
model.wv.get_normed_vectors()

array([[-0.07806021,  0.10098242,  0.02714595, ..., -0.08744665,
        -0.10669693,  0.21572262],
       [-0.20103885,  0.12143141,  0.07397266, ..., -0.11523899,
        -0.12592568,  0.28662336],
       [-0.00235841,  0.07985714,  0.01933833, ..., -0.11048287,
         0.09955258, -0.15811896],
       ...,
       [-0.08080988,  0.02829956, -0.0036123 , ..., -0.09260263,
         0.05942171,  0.11950482],
       [-0.12136049,  0.07075559,  0.10503964, ..., -0.12159384,
         0.11761548,  0.11288447],
       [-0.05857434,  0.08520032,  0.18169335, ..., -0.03976724,
         0.01496945, -0.05501381]], shape=(17310, 100), dtype=float32)

In [17]:
model.wv.get_normed_vectors().shape

(17310, 100)

In [18]:
y = model.wv.index_to_key

In [19]:
len(y)

17310

In [20]:
pca = PCA(n_components = 3)

In [21]:
x = pca.fit_transform(model.wv.get_normed_vectors())

In [22]:
x[:5]

array([[ 0.49046844,  0.02682362,  0.23451215],
       [ 0.4013453 ,  0.5808053 ,  0.37478304],
       [ 0.5306986 , -0.07796423, -0.32975972],
       [-0.02716294,  0.17171265, -0.00947785],
       [ 0.265284  ,  0.54612136,  0.5193675 ]], dtype=float32)

In [23]:
x.shape

(17310, 3)

In [24]:
fig = px.scatter_3d(x[:100], x=0,y=1,z=2, color = y[:100])
fig.show()