In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [4]:
df = df.drop(columns=["id","Unnamed: 32"])

In [5]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [6]:
x_train, x_test, y_train, y_test = train_test_split(
    df.iloc[:,1:],
    df.iloc[:,0],
    test_size=0.2,
)

In [7]:
scaler = StandardScaler()
encoder = LabelEncoder()

In [8]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
x_train

array([[ 1.50591029e+00,  4.58740447e-05,  1.41429048e+00, ...,
         1.28778643e+00,  8.47123014e-01,  2.79321534e-01],
       [-9.34693670e-01, -1.01112001e+00, -9.51896746e-01, ...,
        -1.19847551e+00, -9.25869305e-01, -9.03965284e-01],
       [-1.18353724e-01, -9.69374633e-01, -1.38926171e-01, ...,
        -1.29549353e-01,  8.60268463e-01,  6.52591286e-01],
       ...,
       [-8.92614291e-01, -1.47727677e+00, -9.34426614e-01, ...,
        -1.11748489e+00, -2.06156019e-01, -4.06995672e-01],
       [ 1.11680212e-01,  4.94032879e-01,  1.04030553e-01, ...,
         1.26920932e-01,  2.57221029e-01, -8.62189455e-01],
       [ 1.79485536e+00,  4.94032879e-01,  1.65805976e+00, ...,
         4.56882702e-01, -1.02774653e+00, -7.09734803e-01]],
      shape=(455, 30))

In [10]:
x_test

array([[-0.58403218, -0.85341524, -0.59883756, ..., -0.56569882,
         0.84712301, -0.27732784],
       [-0.38205116, -0.3849393 , -0.43510586, ..., -1.16862896,
        -1.14769874, -1.30761746],
       [ 0.2182813 ,  0.89989075,  0.35389407, ...,  0.8798337 ,
         0.22435741,  0.14422827],
       ...,
       [-1.00763126, -0.00923088, -0.98643073, ..., -1.22997186,
        -0.06155609, -0.47915392],
       [-0.92066721, -2.23101281, -0.93117636, ..., -1.01999618,
        -1.27093732, -0.39940007],
       [ 1.79205007,  0.31081704,  1.74744184, ...,  0.70885351,
         0.58585723, -1.11175935]], shape=(114, 30))

In [11]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,

In [12]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1])

In [13]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [14]:
x_train_tensor

tensor([[ 1.5059e+00,  4.5874e-05,  1.4143e+00,  ...,  1.2878e+00,
          8.4712e-01,  2.7932e-01],
        [-9.3469e-01, -1.0111e+00, -9.5190e-01,  ..., -1.1985e+00,
         -9.2587e-01, -9.0397e-01],
        [-1.1835e-01, -9.6937e-01, -1.3893e-01,  ..., -1.2955e-01,
          8.6027e-01,  6.5259e-01],
        ...,
        [-8.9261e-01, -1.4773e+00, -9.3443e-01,  ..., -1.1175e+00,
         -2.0616e-01, -4.0700e-01],
        [ 1.1168e-01,  4.9403e-01,  1.0403e-01,  ...,  1.2692e-01,
          2.5722e-01, -8.6219e-01],
        [ 1.7949e+00,  4.9403e-01,  1.6581e+00,  ...,  4.5688e-01,
         -1.0277e+00, -7.0973e-01]])

In [15]:
x_test_tensor

tensor([[-0.5840, -0.8534, -0.5988,  ..., -0.5657,  0.8471, -0.2773],
        [-0.3821, -0.3849, -0.4351,  ..., -1.1686, -1.1477, -1.3076],
        [ 0.2183,  0.8999,  0.3539,  ...,  0.8798,  0.2244,  0.1442],
        ...,
        [-1.0076, -0.0092, -0.9864,  ..., -1.2300, -0.0616, -0.4792],
        [-0.9207, -2.2310, -0.9312,  ..., -1.0200, -1.2709, -0.3994],
        [ 1.7921,  0.3108,  1.7474,  ...,  0.7089,  0.5859, -1.1118]])

In [16]:
y_train_tensor

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
        1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
        0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
        0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
        1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 1., 

In [17]:
y_test_tensor

tensor([0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1.,
        0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1.,
        1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
        1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
        0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 0., 1., 0., 0., 1.])

In [25]:
class NeuralNetwork(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid= nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out

In [26]:
learning_rate = 0.1
epochs = 25

In [27]:
loss_function = nn.BCELoss()

In [28]:
model = NeuralNetwork(x_train_tensor.shape[1])

In [29]:
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [30]:
# Define Loop
for epoch in range(epochs):
    # Forward Pass
    y_pred = model(x_train_tensor)

    # Loss Function
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # Clear Gradient
    optimizer.zero_grad()
    
    # Backward Pass
    loss.backward()

    # Parameters Update
    optimizer.step()

    # Print Loss in every Epochs
    print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 0.6756742000579834
Epoch : 2, Loss : 0.5212711095809937
Epoch : 3, Loss : 0.43812090158462524
Epoch : 4, Loss : 0.38648006319999695
Epoch : 5, Loss : 0.35062965750694275
Epoch : 6, Loss : 0.3238389790058136
Epoch : 7, Loss : 0.3027767837047577
Epoch : 8, Loss : 0.2856135964393616
Epoch : 9, Loss : 0.2712555527687073
Epoch : 10, Loss : 0.25900205969810486
Epoch : 11, Loss : 0.24837954342365265
Epoch : 12, Loss : 0.23905372619628906
Epoch : 13, Loss : 0.23078057169914246
Epoch : 14, Loss : 0.22337676584720612
Epoch : 15, Loss : 0.21670131385326385
Epoch : 16, Loss : 0.2106437087059021
Epoch : 17, Loss : 0.2051156461238861
Epoch : 18, Loss : 0.20004580914974213
Epoch : 19, Loss : 0.19537562131881714
Epoch : 20, Loss : 0.19105647504329681
Epoch : 21, Loss : 0.18704771995544434
Epoch : 22, Loss : 0.1833149641752243
Epoch : 23, Loss : 0.17982889711856842
Epoch : 24, Loss : 0.17656435072422028
Epoch : 25, Loss : 0.17349961400032043


In [31]:
model.linear.weight

Parameter containing:
tensor([[ 0.2788,  0.2857,  0.1229,  0.3943,  0.0453,  0.0319,  0.0164,  0.3495,
          0.0614, -0.1573,  0.1395,  0.0735,  0.0969,  0.1222, -0.1075,  0.1615,
          0.0004, -0.0557, -0.0879,  0.0705,  0.2064,  0.2191,  0.3212,  0.2982,
          0.2286,  0.2804,  0.1049,  0.2928,  0.2115,  0.1768]],
       requires_grad=True)

In [32]:
model.linear.bias

Parameter containing:
tensor([-0.1118], requires_grad=True)

In [33]:
with torch.no_grad():
    y_pred = model(x_test_tensor)
    y_pred = (y_pred > 0.5).float()

    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy}")

Accuracy : 0.5138503909111023
